apiVersion: v2
name: nexus-repository-manager

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 79.0.0-bb.3
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 3.79.0-09

description: Sonatype Nexus Repository Manager - Universal Binary repository

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

keywords:
  - artifacts
  - dependency
  - management
  - sonatype
  - nexus
  - repository
  - quickstart
  - ci
  - repository-manager
  - nexus3
home: https://www.sonatype.com/nexus-repository-oss
icon: https://sonatype.github.io/helm3-charts/NexusRepo_Vertical.svg
sources:
  - https://github.com/sonatype/nexus-public
maintainers:
  - email: support@sonatype.com
    name: Sonatype
dependencies:
  - name: gluon
    version: 0.6.2
    repository: oci://registry1.dso.mil/bigbang
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    The [upstream Nexus Repository Manager release notes](https://help.sonatype.com/en/release-notes.html) may help when reviewing this package. We do not track an upstream _chart_ for this package.
  bigbang.dev/applicationVersions: |
    - Nexus: 3.79.0-09
  helm.sh/images: |
    - name: nexus
      image: registry1.dso.mil/ironbank/sonatype/nexus/nexus:3.79.0-09
    - name: ubi9-minimal
      image: registry1.dso.mil/ironbank/redhat/ubi/ubi9-minimal:9.6
