apiVersion: v2
name: nexus-repository-manager
version: 29.1.0-bb.2
appVersion: 3.29.0
description: Sonatype Nexus Repository Manager - Universal Binary repository
type: application
keywords:
  - artifacts
  - dependency
  - management
  - sonatype
  - nexus
  - repository
  - quickstart
  - ci
  - repository-manager
  - nexus3
home: https://www.sonatype.com/nexus-repository-oss
icon: https://sonatype.github.io/helm3-charts/NexusRepo_Vertical.svg
sources:
  - https://github.com/sonatype/nexus-public
maintainers:
  - email:  support@sonatype.com
    name: Sonatype
