---
# -- Big Bang Additions
hostname: nexus
domain: bigbang.dev
istio:
  enabled: false
  hardened: 
    enabled: false
    customAuthorizationPolicies: []
    outboundTrafficPolicyMode: "REGISTRY_ONLY"
    customServiceEntries: []
      # - name: "allow-google"
      #   enabled: true
      #   spec:
      #     exportTo:
      #       - "."
      #     hosts:
      #       - google.com
      #     location: MESH_EXTERNAL
      #     ports:
      #       - number: 443
      #         protocol: TLS
      #         name: https
      #     resolution: DNS
    monitoring:
      enabled: true
      namespaces:
        - monitoring
      principals:
        - cluster.local/ns/monitoring/sa/monitoring-monitoring-kube-prometheus
  injection: disabled
  nexus:
    gateways:
    - "istio-system/main"
    hosts:
    - "{{ .Values.hostname }}.{{ .Values.domain }}"
  mtls:
    # STRICT = Allow only mutual TLS traffic
    # PERMISSIVE = Allow both plain text and mutual TLS traffic
    mode: STRICT

networkPolicies:
  enabled: false
  ingressLabels:
    app: istio-ingressgateway
    istio: ingressgateway
  # Additional network policies
  # ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/    
  additionalPolicies: []

# External database - See docs/general.md
custom_admin_password: ""
custom_metrics_password: ""

monitoring:
  enabled: false
  serviceMonitor:
    createMetricsUser: false
    additionalLabels: {}
    # ServiceMonitor namespace. Default to nexus-repository-manager namespace.
    # namespace:
    scheme: "http"
    # tlsConfig: {}

license_key: ""
license:
  mountPath: /nexus-data/sonatype-license.lic
  subPath: sonatype-license.lic
sso:
  enabled: false
  idp_data:
    entityId: ""
    usernameAttribute: ""
    firstNameAttribute: ""
    lastNameAttribute: ""
    emailAttribute: ""
    groupsAttribute: ""
    validateResponseSignature: true
    validateAssertionSignature: true
    idpMetadata: ''
  realm:
    - "NexusAuthenticatingRealm"
  role:
    - id: "nexus"
      name: "nexus"
      description: "nexus group"
      privileges:
        - "nx-all"
      roles:
        - "nx-admin"

proxy:
  enabled: false
  request:
    tid: 1
    action: coreui_HttpSettings
    method: update
    type: rpc
    data:
    - userAgentSuffix: ~
      timeout: ~
      retries: ~
      httpEnabled: false
      httpHost: ~
      httpPort: ~
      httpAuthEnabled: ~
      httpAuthUsername: ~
      httpAuthPassword: ~
      httpAuthNtlmHost: ~
      httpAuthNtlmDomain: ~
      httpsEnabled: false
      httpsHost: ~
      httpsPort: ~
      httpsAuthEnabled: ~
      httpsAuthUsername: ~
      httpsAuthPassword: ~
      httpsAuthNtlmHost: ~
      httpsAuthNtlmDomain: ~
      nonProxyHosts: []

job_image:
  repository: registry1.dso.mil/ironbank/redhat/ubi/ubi9-minimal
  tag: 9.4 
  pullPolicy: IfNotPresent

openshift: false

bbtests:
  enabled: false
  cypress:
    artifacts: true
    envs:
      cypress_nexus_url: "http://nexus-nexus-repository-manager:8081"
      cypress_nexus_user: "admin"
    secretEnvs:
      - name: cypress_nexus_pass
        valueFrom:
          secretKeyRef:
            name: nexus-repository-manager-secret
            key: admin.password
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 2
        memory: 4Gi

  scripts:
    image: "registry1.dso.mil/bigbang-ci/devops-tester:1.1.1"
    additionalVolumes:
      - name: docker-config
        secret:
          secretName: private-registry
          items:
          - key: .dockerconfigjson
            path: auth.json
    additionalVolumeMounts:
      - name: docker-config
        mountPath: /.docker/
    envs:
      docker_host: "nexus-nexus-repository-manager-docker-5000:5000"
      docker_user: "admin"
    secretEnvs:
      - name: docker_password
        valueFrom:
          secretKeyRef:
            name: nexus-repository-manager-secret
            key: admin.password

# -- End of BigBang Additions

statefulset:
  # This is not supported
  enabled: false
deploymentStrategy: Recreate
image:
  # IB Nexus Image
  repository: registry1.dso.mil/ironbank/sonatype/nexus/nexus
  tag: 3.73.0-12
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: private-registry

nexus:
  # BB affinity added
  affinity: {}

  # BB extraLabels added
  extraLabels:
    app: nexus-repository-manager

  # BB blobstore added
  blobstores:
    enabled: false
    # -- `.type` must be one of `s3`, `azure`, or `file`.
    # `.blobstore_data` must match the schema described in the [Nexus blobstore API docs](https://help.sonatype.com/en/blob-store-api.html) for more details.
    blobstore:
      - name: "test-nexus-blobstore"
        type: "s3"
        blobstore_data:
          name: "test-nexus-blobstore"
          bucketConfiguration:
            bucket:
              region: "your-bucket-region"
              name: "your-bucket-name"
              prefix: ""
              expiration: 3
            bucketSecurity:
              accessKeyId: "your-accessKeyId"
              secretAccessKey: "your-secretAccessKey"
              role: "your-role"
              sessionToken: "your-sessionToken"

  # BB repository added
  repository:
    # Raw format Repositories are currently the only supported format.
    enabled: false
    repo:
      - name: "test-nexus"
        format: "raw"
        type: "hosted"
        repo_data:
          name: "test-nexus"
          online: true
          storage:
            blobStoreName: "default"
            strictContentTypeValidation: true
            writePolicy: "allow_once"
          cleanup:
            policyNames:
              - "string"
          component:
            proprietaryComponents: true
          raw:
            contentDisposition: "ATTACHMENT"

  docker:
    enabled: false
    # registries:
    #   - host: chart.local
    #     port: 5000
    #     secretName: registry-secret
  env:
    # minimum recommended memory settings for a small, person instance from
    # https://help.sonatype.com/repomanager3/product-information/system-requirements
    - name: INSTALL4J_ADD_VM_PARAMS
      # info about fips option: https://access.redhat.com/documentation/en-us/openjdk/8/pdf/configuring_openjdk_8_on_rhel_with_fips/openjdk-8-configuring_openjdk_8_on_rhel_with_fips-en-us.pdf
      value: "-Dcom.redhat.fips=false -Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    - name: NEXUS_SECURITY_RANDOMPASSWORD
      value: "true"
  properties:
    override: false
    data: {}
      # nexus.scripts.allowCreation: true
      # See this article for ldap configuration options https://support.sonatype.com/hc/en-us/articles/216597138-Setting-Advanced-LDAP-Connection-Properties-in-Nexus-Repository-Manager
      # nexus.ldap.env.java.naming.security.authentication: simple
      # Reference the external database section in docs/general.md
      # nexus.datastore.enabled: true
  # nodeSelector:
  #   cloud.google.com/gke-nodepool: default-pool
  resources:
  # minimum recommended memory settings for a small, person instance from
  # https://help.sonatype.com/repomanager3/product-information/system-requirements
    requests:
      cpu: 4
      memory: 8Gi
    limits:
      cpu: 4
      memory: 8Gi

  # The ports should only be changed if the nexus image uses a different port
  nexusPort: 8081

  # Default the pods UID and GID to match the nexus3 container.
  # Customize or remove these values from the securityContext as appropriate for
  # your deployment environment.
  securityContext:
    runAsNonRoot: true
    fsGroup: 2000
    runAsUser: 200
    runAsGroup: 2000

  containerSecurityContext:
    capabilities:
      drop:
        - ALL

  podAnnotations: {}
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 6
    timeoutSeconds: 10
    path: /
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 6
    timeoutSeconds: 10
    path: /
  # hostAliases allows the modification of the hosts file inside a container
  hostAliases: []
  # - ip: "192.168.1.10"
  #   hostnames:
  #   - "example.com"
  #   - "www.example.com"

nameOverride: ""
fullnameOverride: ""

deployment:
  # # Add annotations in deployment to enhance deployment configurations
  annotations: {}
  # # Add init containers. e.g. to be used to give specific permissions for nexus-data.
  # # Add your own init container or uncomment and modify the given example.
  initContainers:
  #   - name: fmp-volume-permission
  #   image: busybox
  #   imagePullPolicy: IfNotPresent
  #   command: ['chown','-R', '200', '/nexus-data']
  #   volumeMounts:
  #     - name: nexus-data
  #       mountPath: /nexus-data
  # Uncomment and modify this to run a command after starting the nexus container.
  postStart:
    command:    # '["/bin/sh", "-c", "ls"]'
  preStart:
    command:    # '["/bin/rm", "-f", "/path/to/lockfile"]'
  terminationGracePeriodSeconds: 120
  additionalContainers:
  additionalVolumes:
  additionalVolumeMounts:

ingress:
  enabled: false
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hostPath: /
  hostRepo: repo.demo
  # tls:
  #   - secretName: nexus-local-tls
  #     hosts:
  #       - repo.demo


service:
  name: nexus3
  enabled: true
  labels: {}
  annotations: {}
  type: ClusterIP


route:
  enabled: false
  name: docker
  portName: docker
  labels:
  annotations:
  # path: /docker

nexusProxyRoute:
  enabled: false
  labels:
  annotations:
  # path: /nexus

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  ## If defined, storageClass: <storageClass>
  ## If set to "-", storageClass: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClass spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # existingClaim:
  # annotations:
  #  "helm.sh/resource-policy": keep
  # storageClass: "-"
  storageSize: 8Gi
  # If PersistentDisk already exists you can create a PV for it by including the 2 following keypairs.
  # pdName: nexus-data-disk
  # fsType: ext4

tolerations: []

# Enable configmap and add data in configmap
config:
  enabled: false
  mountPath: /sonatype-nexus-conf
  data: []

# # To use an additional secret, set enable to true and add data
secret:
  enabled: true
  mountPath: /nexus-data/admin.password
  subPath: admin.password
  readOnly: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
