{{- if and .Values.networkPolicies.enabled .Values.nexus.repository.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-workflow-communications
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: nexus-repository-manager
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: nexus-repository-manager
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: nexus-repository-manager
{{- end }}