{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-outreach-manager
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: nexus-repository-manager
  policyTypes:
  - Egress
  egress:
    - ports:
      - port: 443
        protocol: TCP
{{- end }}
