{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kube-api-dns-egress
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: UDP
    {{- if .Values.openshift }}
    - port: 5353
      protocol: UDP
    {{- end }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nexus-repository-manager
  policyTypes:
  - Egress
{{- end }}
