{{- if and .Values.networkPolicies.enabled .Values.sso.enabled .Values.secret.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  name: repos-egress-dns
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      job-name: repo
  policyTypes:
  - Egress
  # Allow access to DNS
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - port: 53
      protocol: UDP
    {{- if .Values.openshift }}
    - port: 5353
      protocol: UDP
    {{- end }}
{{- end }}
