{{- if .Values.nexus.repository.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nexus.name" . }}-realms
  labels: {{- include "nexus.labels" . | nindent 4 }}
{{- if .Values.nexus.extraLabels }}
  {{- with .Values.nexus.extraLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
data:
  {{- if and .Values.sso.enabled .Values.license_key }}
  realms: '[{{ join "\",\"" .Values.realms | printf "\"%s\""}}, "SamlRealm"]'
  {{- else }}
  realms: '[{{ join "\",\"" .Values.realms | printf "\"%s\""}}]'
  {{- end }}
{{- end }}
