{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nexus.name" . }}-proxy
  labels: {{- include "nexus.labels" . | nindent 4 }}
{{- if .Values.nexus.extraLabels }}
  {{- with .Values.nexus.extraLabels }}
    {{ toYaml . }}
  {{- end }}
{{- end }}
data:
  proxy: {{ .Values.proxy.request | toJson | quote }}
{{- end }}

