{{- if .Values.license_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.name" . }}-license
  labels:
{{ include "nexus.labels" . | indent 4 }}
    {{- if .Values.nexus.extraLabels }}
      {{- with .Values.nexus.extraLabels }}
        {{ toYaml . | indent 4 }}
      {{- end }}
    {{- end }}
data:
{{ include "nexus.licenseKey" . | indent 2 }}
{{- end -}}