{{- if .Values.proxy.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  creationTimestamp: null
  name: proxy
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 90
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- if .Values.nexus.securityContext }}
      securityContext:
        {{ toYaml .Values.nexus.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.job_image.repository }}:{{ .Values.job_image.tag }}"
        imagePullPolicy: {{ .Values.job_image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.nexus.containerSecurityContext | nindent 10 }}
        name: proxy
        command:
          - sh
        args:
          - -c
          - |
            {{- if and .Values.istio.enabled (eq .Values.istio.injection "enabled") }} 
            until curl --head localhost:15000; do echo "Waiting for Istio proxy sidecar"; sleep 10; done; echo "Sidecar available"  &&
            {{- end }}
            BASE_URL="http://{{ include "nexus.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.nexus.nexusPort }}"
            # proxy
            curl -X POST \
                 -u admin:"$API_CREDENTIALS" \
                 "$BASE_URL/service/extdirect" \
                 -H "Content-Type: application/json" \
                 -d "$PROXY" &&
            {{- if and .Values.istio.enabled (eq .Values.istio.injection "enabled") }}     
            curl -fsI -X POST http://localhost:15020/quitquitquit &&
            {{- end }}
            exit
        env:
        - name: API_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: {{ template "nexus.name" . }}-secret
              key: admin.password
        - name: PROXY
          valueFrom:
            configMapKeyRef:
              name: {{ template "nexus.name" . }}-proxy
              key: proxy
        resources: {}
      restartPolicy: Never
status: {}
{{- end }}
