{{- if .Values.secret.enabled -}}

{{- $nexusAdminPass := (include "nexus.defaultAdminPassword" . | b64enc ) }}

{{- if .Release.IsUpgrade }}
{{- $adminPassSecret := (lookup "v1" "Secret" .Release.Namespace (print (include "nexus.name" .) "-secret")) }}
{{- $nexusAdminPass = (index $adminPassSecret.data "admin.password") }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.name" . }}-secret
  labels:
{{ include "nexus.labels" . | indent 4 }}
{{- if .Values.nexus.extraLabels }}
  {{- with .Values.nexus.extraLabels }}
    {{ toYaml . }}
  {{- end }}
{{- end }}
data:
  admin.password: {{ $nexusAdminPass }}
  admin.username: YWRtaW4K
{{- end }}
