{{- if .Values.secret.enabled -}}
{{- if not (lookup "v1" "Secret" "" "{{ template 'nexus.name' . }}-secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.name" . }}-secret
  labels:
{{ include "nexus.labels" . | indent 4 }}
    {{- if .Values.nexus.extraLabels }}
      {{- with .Values.nexus.extraLabels }}
        {{ toYaml . | indent 4 }}
      {{- end }}
    {{- end }}
data:
  admin.password: {{ randAlphaNum 12 | b64enc | quote }}
  admin.username: YWRtaW4K
{{- end}}
{{- end}}
