{{- if .Values.istio.enabled -}}
{{- $serviceName := include "nexus.fullname" . -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "nexus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "nexus.name" . }}
    helm.sh/chart: {{ include "nexus.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: nexus-repository-manager
    app.kubernetes.io/component: {{ include "nexus.name" . }}
spec:
  gateways:
  {{- range .Values.istio.nexus.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.nexus.hosts }}
    - {{ tpl . $ }}
  {{- end }}

  http:
    - route:
        - destination:
            port:
              number: {{ .Values.nexus.nexusPort }}
            host: {{ $serviceName }}
{{- $fullName := include "nexus.fullname" . -}}
{{ if .Values.nexus.docker.enabled }}
{{ range $registry := .Values.nexus.docker.registries }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $fullName | trunc 49 }}-docker-{{ $registry.port }}
  namespace: {{ $.Release.Namespace }}
spec:
  gateways:
  {{- range $.Values.istio.nexus.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  - {{ tpl $registry.host $ | quote }}
  http:
  - route:
    - destination:
        port:
          number: {{ $registry.port }}
        host: {{ $fullName | trunc 49 }}-docker-{{ $registry.port }}
{{- end }}
{{- end }}
{{- end }} 
